package com.bjit.training.model;
// Generated Feb 11, 2018 11:30:26 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "countries", catalog = "dbtest")
public class Country implements java.io.Serializable {

	private Integer id;
	private String code;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set<User> usersesForShippingCountry = new HashSet<User>(0);
	private Set<User> usersesForBillingCountry = new HashSet<User>(0);
	public Country() {
	}

	public Country(String code, Date createdAt, Date updatedAt) {
		this.code = code;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Country(String code, String name, Date createdAt, Date updatedAt, Set<User> usersesForShippingCountry,
			Set<User> usersesForBillingCountry) {
		this.code = code;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.usersesForShippingCountry = usersesForShippingCountry;
		this.usersesForBillingCountry = usersesForBillingCountry;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countriesByShippingCountry")
	public Set<User> getUsersesForShippingCountry() {
		return this.usersesForShippingCountry;
	}

	public void setUsersesForShippingCountry(Set<User> usersesForShippingCountry) {
		this.usersesForShippingCountry = usersesForShippingCountry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countriesByBillingCountry")
	public Set<User> getUsersesForBillingCountry() {
		return this.usersesForBillingCountry;
	}

	public void setUsersesForBillingCountry(Set<User> usersesForBillingCountry) {
		this.usersesForBillingCountry = usersesForBillingCountry;
	}

}
