package com.bjit.training.model;
// Generated Feb 11, 2018 11:30:26 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderProducts generated by hbm2java
 */
@Entity
@Table(name = "order_products", catalog = "dbtest")
public class OrderProducts implements java.io.Serializable {

	private Integer id;
	private Orders orders;
	private ProductAttributeItems productAttributeItems;
	private Products products;
	private int unitPrice;
	private int quantity;
	private Integer attributeItemId;
	private Date createdAt;
	private Date updatedAt;

	public OrderProducts() {
	}

	public OrderProducts(Orders orders, ProductAttributeItems productAttributeItems, Products products, int unitPrice,
			int quantity, Date createdAt) {
		this.orders = orders;
		this.productAttributeItems = productAttributeItems;
		this.products = products;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
		this.createdAt = createdAt;
	}

	public OrderProducts(Orders orders, ProductAttributeItems productAttributeItems, Products products, int unitPrice,
			int quantity, Integer attributeItemId, Date createdAt, Date updatedAt) {
		this.orders = orders;
		this.productAttributeItems = productAttributeItems;
		this.products = products;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
		this.attributeItemId = attributeItemId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attribute_id", nullable = false)
	public ProductAttributeItems getProductAttributeItems() {
		return this.productAttributeItems;
	}

	public void setProductAttributeItems(ProductAttributeItems productAttributeItems) {
		this.productAttributeItems = productAttributeItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "unit_price", nullable = false)
	public int getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(int unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "attribute_item_id")
	public Integer getAttributeItemId() {
		return this.attributeItemId;
	}

	public void setAttributeItemId(Integer attributeItemId) {
		this.attributeItemId = attributeItemId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
