package com.bjit.training.model;
// Generated Feb 11, 2018 11:30:26 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "dbtest")
public class Orders implements java.io.Serializable {

	private Integer id;
	private Users users;
	private int vat;
	private int shippingCost;
	private byte status;
	private Date createdAt;
	private Date updatedAt;
	/*private Set<OrderProducts> orderProductses = new HashSet<OrderProducts>(0);
	private Set<Payments> paymentses = new HashSet<Payments>(0);
*/
	public Orders() {
	}

	public Orders(Users users, int vat, int shippingCost, byte status, Date createdAt, Date updatedAt) {
		this.users = users;
		this.vat = vat;
		this.shippingCost = shippingCost;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/*public Orders(Users users, int vat, int shippingCost, byte status, Date createdAt, Date updatedAt,
			Set<OrderProducts> orderProductses, Set<Payments> paymentses) {
		this.users = users;
		this.vat = vat;
		this.shippingCost = shippingCost;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderProductses = orderProductses;
		this.paymentses = paymentses;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "vat", nullable = false)
	public int getVat() {
		return this.vat;
	}

	public void setVat(int vat) {
		this.vat = vat;
	}

	@Column(name = "shipping_cost", nullable = false)
	public int getShippingCost() {
		return this.shippingCost;
	}

	public void setShippingCost(int shippingCost) {
		this.shippingCost = shippingCost;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<OrderProducts> getOrderProductses() {
		return this.orderProductses;
	}

	public void setOrderProductses(Set<OrderProducts> orderProductses) {
		this.orderProductses = orderProductses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<Payments> getPaymentses() {
		return this.paymentses;
	}

	public void setPaymentses(Set<Payments> paymentses) {
		this.paymentses = paymentses;
	}*/

}
