package com.bjit.training.model;
// Generated Feb 11, 2018 11:30:26 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "dbtest", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Users implements java.io.Serializable {

	private Integer id;
	private Countries countriesByShippingCountry;
	private Countries countriesByBillingCountry;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private String contactNo;
	private byte status;
	private String billingAddress;
	private String billingCity;
	private String billingZipCode;
	private String shippingAddress;
	private String shippingCity;
	private String shippingZipCode;
	private Date createdAt;
	private Date updatedAt;
	/*private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Ratings> ratingses = new HashSet<Ratings>(0);
*/
	public Users() {
	}

	public Users(Countries countriesByShippingCountry, Countries countriesByBillingCountry, String firstName,
			String lastName, String email, String password, String contactNo, byte status, String billingAddress,
			String billingCity, String billingZipCode, String shippingAddress, String shippingCity,
			String shippingZipCode, Date createdAt, Date updatedAt) {
		this.countriesByShippingCountry = countriesByShippingCountry;
		this.countriesByBillingCountry = countriesByBillingCountry;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.contactNo = contactNo;
		this.status = status;
		this.billingAddress = billingAddress;
		this.billingCity = billingCity;
		this.billingZipCode = billingZipCode;
		this.shippingAddress = shippingAddress;
		this.shippingCity = shippingCity;
		this.shippingZipCode = shippingZipCode;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/*public Users(Countries countriesByShippingCountry, Countries countriesByBillingCountry, String firstName,
			String lastName, String email, String password, String contactNo, byte status, String billingAddress,
			String billingCity, String billingZipCode, String shippingAddress, String shippingCity,
			String shippingZipCode, Date createdAt, Date updatedAt, Set<Orders> orderses, Set<Ratings> ratingses) {
		this.countriesByShippingCountry = countriesByShippingCountry;
		this.countriesByBillingCountry = countriesByBillingCountry;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.contactNo = contactNo;
		this.status = status;
		this.billingAddress = billingAddress;
		this.billingCity = billingCity;
		this.billingZipCode = billingZipCode;
		this.shippingAddress = shippingAddress;
		this.shippingCity = shippingCity;
		this.shippingZipCode = shippingZipCode;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderses = orderses;
		this.ratingses = ratingses;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_country", nullable = false)
	public Countries getCountriesByShippingCountry() {
		return this.countriesByShippingCountry;
	}

	public void setCountriesByShippingCountry(Countries countriesByShippingCountry) {
		this.countriesByShippingCountry = countriesByShippingCountry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billing_country", nullable = false)
	public Countries getCountriesByBillingCountry() {
		return this.countriesByBillingCountry;
	}

	public void setCountriesByBillingCountry(Countries countriesByBillingCountry) {
		this.countriesByBillingCountry = countriesByBillingCountry;
	}

	@Column(name = "first_name", nullable = false, length = 32)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 32)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", unique = true, nullable = false, length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "contact_no", nullable = false, length = 16)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "billing_address", nullable = false, length = 64)
	public String getBillingAddress() {
		return this.billingAddress;
	}

	public void setBillingAddress(String billingAddress) {
		this.billingAddress = billingAddress;
	}

	@Column(name = "billing_city", nullable = false, length = 16)
	public String getBillingCity() {
		return this.billingCity;
	}

	public void setBillingCity(String billingCity) {
		this.billingCity = billingCity;
	}

	@Column(name = "billing_zip_code", nullable = false, length = 8)
	public String getBillingZipCode() {
		return this.billingZipCode;
	}

	public void setBillingZipCode(String billingZipCode) {
		this.billingZipCode = billingZipCode;
	}

	@Column(name = "shipping_address", nullable = false, length = 64)
	public String getShippingAddress() {
		return this.shippingAddress;
	}

	public void setShippingAddress(String shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	@Column(name = "shipping_city", nullable = false, length = 16)
	public String getShippingCity() {
		return this.shippingCity;
	}

	public void setShippingCity(String shippingCity) {
		this.shippingCity = shippingCity;
	}

	@Column(name = "shipping_zip_code", nullable = false, length = 8)
	public String getShippingZipCode() {
		return this.shippingZipCode;
	}

	public void setShippingZipCode(String shippingZipCode) {
		this.shippingZipCode = shippingZipCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Ratings> getRatingses() {
		return this.ratingses;
	}

	public void setRatingses(Set<Ratings> ratingses) {
		this.ratingses = ratingses;
	}*/

}
